include:
  - local: '.gitlab/ci/deploy.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - test
  - build
  - deploy

test:
 stage: test
 image: rust:latest
 before_script:
   - apt update
   - apt install cmake -y
 script:
   - RUST_BACKTRACE=1 cargo test -p squiid -p squiid-engine -p squiid-parser --verbose
