name: squiid
version: '$VERSION'
summary: Squiid is a modular calculator written in Rust.
description: |
  Squiid is a modular calculator written in Rust. It is currently very early
  in development but it is intended to be the successor to
  ImaginaryInfinity Calculator

grade: stable
base: core18
confinement: strict
build-packages:
  - cmake

parts:
  squiid:
    plugin: rust
    source: .

apps:
  squiid:
    command: squiid