name: squiid
version: '$VERSION'
summary: Squiid is a modular calculator written in Rust.
description: |
  Squiid is a modular calculator written in Rust. It is currently very early
  in development but it is intended to be the successor to
  ImaginaryInfinity Calculator
website: https://imaginaryinfinity.net
contact: imaginaryinfinity@googlegroups.com

license: GPL-3.0

grade: stable
base: core20
confinement: strict
build-packages:
  - cmake

parts:
  squiid:
    plugin: rust
    source: .

plugs:
  squiid-network:
    interface: network-bind
    listen: [20000]
    auto-connect: true

apps:
  squiid:
    command: bin/squiid