name: squiid
version: '$VERSION'
summary: Do advanced algebraic and RPN calculations.
description: |
  Advanced calculator written in Rust, featuring a terminal user interface
  supporting both RPN and algebraic input.
website: https://imaginaryinfinity.net
contact: imaginaryinfinity@googlegroups.com

license: GPL-3.0

grade: stable
base: core20
confinement: strict
build-packages:
  - cmake

parts:
  squiid:
    plugin: rust
    source: .

plugs:
  squiid-network:
    interface: network-bind

apps:
  squiid:
    command: bin/squiid